Add missing Makefile dependencies
* With very high -j parallelism, we get failures in Gentoo:

  In file included from lib/ext2fs/blknum.c:15:
  lib/ext2fs/ext2fs.h:105:10: fatal error: ext2fs/ext2_err.h: No such file or directory
    105 | #include <ext2fs/ext2_err.h>
        |          ^~~~~~~~~~~~~~~~~~~
  compilation terminated.
  In file included from lib/ext2fs/fallocate.c:19:
  lib/ext2fs/ext2fs.h:105:10: fatal error: ext2fs/ext2_err.h: No such file or directory
    105 | #include <ext2fs/ext2_err.h>
        |          ^~~~~~~~~~~~~~~~~~~

Bug: https://bugs.gentoo.org/806875#c17
Signed-off-by: David Seifert <soap@gentoo.org>